Meteor.$fn.addRecentMethod 'data', 'project', 'projects'
Meteor.$fn.addRecentMethod 'data', 'specimen', 'specimens'
Meteor.$fn.addRecentMethod 'data', 'clinical', 'clinicals'
Meteor.$fn.addRecentMethod 'data', 'bacterium', 'bacteria'
Meteor.$fn.addRecentMethod 'data', 'construct', 'constructs'
Meteor.$fn.addRecentMethod 'data', 'location', 'locations'
